server:
  port: 8001
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=Asia/Shanghai"
    username: root
    password: root
  application:
    name: bookProvider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848