server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # --- 图书服务 ---
        - id: book-service-route
          uri: http://localhost:8001
          predicates:
            # 在这里添加了 /updateInfo
            - Path=/book/**,/get/**,/status/**,/list,/search,/del/**,/addbook,/find/**,/updateInfo

        # --- 登录服务 ---
        - id: login-service-route
          uri: http://localhost:8003
          predicates:
            - Path=/getUserByUsername/**,/findUserByUserId/**

        # --- 订单服务 ---
        - id: order-service-route
          uri: http://localhost:8004
          predicates:
            - Path=/order/**

        # --- 库存服务 ---
        - id: inventory-service-route
          uri: http://localhost:8005
          predicates:
            - Path=/inventory/**

        # --- 页面前端 ---
        - id: consumer-service-route
          uri: http://localhost:80
          predicates:
            - Path=/consumer/**,/loginview